name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK 36
        run: |
          yes | sdkmanager "platform-tools"
          yes | sdkmanager "platforms;android-36"
          yes | sdkmanager "build-tools;36.0.0"

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > n1ckverse-release.jks

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew clean assemblePlayRelease --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: N1ckVerse-Release
          path: app/build/outputs/apk/play/release/*.apk
